from app.schemas.auth import LoginRequest, RegisterRequest, TokenResponse, UserPublic
from app.schemas.school import (
    MistakeTypeCreate,
    MistakeTypeUpdate,
    SkillCreate,
    SkillUpdate,
    SubjectCreate,
    SubjectUpdate,
    TopicCreate,
    TopicUpdate,
)
from app.schemas.students import (
    LearningGoalCreate,
    LearningGoalUpdate,
    StudentCreate,
    StudentGroupCreate,
    StudentGroupMemberCreate,
    StudentGroupUpdate,
    StudentUpdate,
)
from app.schemas.reports import PeriodReportCreate, ReportUpdate
from app.schemas.tutor import (
    HomeworkCreate,
    HomeworkUpdate,
    LessonCreate,
    LessonFullCreate,
    LessonMistakeCreate,
    LessonMistakeUpdate,
    LessonObservationCreate,
    LessonObservationUpdate,
    LessonTopicResultCreate,
    LessonTopicResultUpdate,
    LessonUpdate,
)

__all__ = [
    "HomeworkCreate",
    "LoginRequest",
    "RegisterRequest",
    "TokenResponse",
    "UserPublic",
    "HomeworkUpdate",
    "LearningGoalCreate",
    "LearningGoalUpdate",
    "LessonCreate",
    "LessonFullCreate",
    "LessonMistakeCreate",
    "LessonMistakeUpdate",
    "LessonObservationCreate",
    "LessonObservationUpdate",
    "LessonTopicResultCreate",
    "LessonTopicResultUpdate",
    "LessonUpdate",
    "MistakeTypeCreate",
    "MistakeTypeUpdate",
    "PeriodReportCreate",
    "ReportUpdate",
    "SkillCreate",
    "SkillUpdate",
    "StudentCreate",
    "StudentGroupCreate",
    "StudentGroupMemberCreate",
    "StudentGroupUpdate",
    "StudentUpdate",
    "SubjectCreate",
    "SubjectUpdate",
    "TopicCreate",
    "TopicUpdate",
]
